### ISSUE TITLE
Catkinize pr2_pbd and make it available for Hydro

### ISSUE THREAD

**Issue by UltronDestroyer** [PR2/pr2_pbd#22]
Do you mind if I do this? @mayacakmak @mbforbes

**Comment by mbforbes** [comment]
Wow, thanks for offering! Actually, though, you should hold off---we had someone work on this for quite a few months and it's near ready. 

https://github.com/vovakkk/pr2_pbd/tree/hydro

If you'd like to contribute, I would check that out, and send PRs there. Let me know if you get stuck and I can ask @mayacakmak about sending some docs your way.

**Comment by UltronDestroyer** [comment]
You're right that it would be a lot of work. It depends on the object manipulation stacks and pr2 kinematics. Pr2 kinemagics is in hydro now, and object manipulation will be soon. After that, catkinization of this shouldn't take too long.

**Comment by jstnhuang** [comment]
This is finally complete and hydro-devel is the default branch now.
