### ISSUE TITLE
Adjusting poses in rviz is really slow

### ISSUE THREAD

**Issue by jstnhuang** [PR2/pr2_pbd#36]
Whenever I want to adjust a pose in rviz (because no IK solution was found for it), it goes really slowly. I'll drag the interactive marker in some direction. Then, the marker will snap back, and the gripper marker will slowly jump a tiny bit (maybe 0.5cm?) at a time in the direction I moved it, on the order of a few seconds for a tiny jump and maybe a minute just to drag the marker a few centimeters.

**Comment by Vivekparam** [comment]
Was this a problem in groovy as well?

**Comment by mbforbes** [comment]
I remember this being a lesser but existent problem in groovy. You'd sometimes see this behavior, but it wouldn't take nearly a minute to do a substantial (~1 meter) drag—maybe only a few seconds. I think I remember it getting worse when there was a lot going on (i.e. high CPU load) but I'm not sure.

**Comment by jstnhuang** [comment]
Fixing MoveIt/TF and limiting the queue size for the marker server might help. In my most recent tests it's been fine. Closing for now.
